"""Photographic ground textures for the battlefield (PROJECT 1864): top-down meadow grass, a stubble/grain field and
trampled dirt, generated by ComfyUI (SDXL) and made seamless (the picture rolled by half and blended over its own
seams), 1024 px, written over SourceAssets/Battle1864/Textures/T_Ground_*_D.png (the normal maps are derived
from their luminance). Import with Content/Python/import_battle_graphics.py.
Usage: python Tools/Battle/make_ground_photos.py --base <comfy url>"""
import argparse, os, subprocess, sys
import numpy as np
from PIL import Image, ImageFilter

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..')
OUT = os.path.join(ROOT, 'SourceAssets', 'Battle1864', 'Textures')
CLIENT = r"R:\Onedrive\Dokumenter\Unreal Projects\Game1864\pinokio_agent\skills\api\comfy.git\clients\txt2img.py"
NEG = "perspective, horizon, sky, objects, people, animals, flowers close up, text, watermark, frame, vignette, shadows of trees, blurry"
TEXTURES = {
    'T_Ground_Grass': "seamless top-down photograph of a summer meadow lawn, dense short green grass with a few dry yellow blades and clover, even natural daylight, flat lighting, high detail, texture map",
    'T_Ground_Field': "seamless top-down photograph of a ripe golden wheat stubble field, straw and soil, even daylight, flat lighting, high detail, texture map",
    'T_Ground_Dirt': "seamless top-down photograph of a trampled dirt country road, packed brown earth with small stones and wheel ruts, even daylight, flat lighting, high detail, texture map",
}


def make_seamless(img):
    a = np.asarray(img).astype(np.float32)
    h, w = a.shape[:2]
    rolled = np.roll(np.roll(a, h // 2, axis=0), w // 2, axis=1)
    # Weight of the original: 1 in the middle, 0 at the edges (where the rolled copy has its middle).
    y = np.abs(np.linspace(-1, 1, h))[:, None]
    x = np.abs(np.linspace(-1, 1, w))[None, :]
    edge = np.clip(np.maximum(x, y) * 1.6 - 0.6, 0, 1)
    edge = edge * edge * (3 - 2 * edge)
    out = a * (1 - edge[:, :, None]) + rolled * edge[:, :, None]
    return Image.fromarray(np.clip(out, 0, 255).astype(np.uint8))


def normal_from(img, strength=2.5):
    h = np.asarray(img.convert('L').filter(ImageFilter.GaussianBlur(1))).astype(np.float32) / 255.0
    dx = (np.roll(h, -1, 1) - np.roll(h, 1, 1)) * strength
    dy = (np.roll(h, -1, 0) - np.roll(h, 1, 0)) * strength
    n = np.dstack([-dx, -dy, np.ones_like(h)])
    n /= np.linalg.norm(n, axis=2, keepdims=True)
    return Image.fromarray(((n * 0.5 + 0.5) * 255).astype(np.uint8))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--base', required=True)
    ap.add_argument('--ckpt', default='juggernautXL_ragnarokBy.safetensors')
    a = ap.parse_args()
    for name, prompt in TEXTURES.items():
        raw = os.path.join(OUT, '_raw_' + name + '.png')
        subprocess.check_call([sys.executable, CLIENT, '--base', a.base, '--ckpt', a.ckpt, '--out', raw, '--seed', '1864', '--prompt', prompt, '--negative', NEG])
        img = make_seamless(Image.open(raw).convert('RGB'))
        img.save(os.path.join(OUT, name + '_D.png'))
        normal_from(img).save(os.path.join(OUT, name + '_N.png'))
        os.remove(raw)
        print('ground', name)


if __name__ == '__main__':
    main()
