

[/Script/CommonUI.CommonUISettings]
CommonButtonAcceptKeyHandling=TriggerClick

[ConsoleVariables]
CommonUI.CheckKeyboardFocusAndParentage=1
CommonUI.DisallowUserFocusedWidgetForPendingFocusRecipient=1
CommonUI.FallbackToDesiredOnAutoRestoreFailure=1

[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=0A1C2ABD4D5EFBE73795F9B7B7BF7CC9

; Slaglyde refereres med bløde stier og skal med i pakkede spil.
[/Script/DeveloperToolSettings.ProjectPackagingSettings]
+DirectoriesToAlwaysCook=(Path="/Game/Battle/Audio")

; Gemte VAT-modeller og deres shader indlaeses via konstruerede asset-stier.
+DirectoriesToAlwaysCook=(Path="/Game/Battle/VAT")
+DirectoriesToAlwaysCook=(Path="/Game/Battle/Materials")
