"""Building cards for the town panel (PROJECT 1864): an isometric painterly picture of each building that has none,
generated by ComfyUI (SDXL, JuggernautXL) through pinokio_agent/skills/api/comfy.git/clients/txt2img.py, the white
background keyed out to transparency (flood fill from the edges), 512 x 512, written to
Reference/Campaign1851/Buildings/T_Bld_<Key>.png (imported by Tools/Campaign/import_building_cards.py).
Usage: python Tools/Campaign/make_building_cards.py --base <comfy url> [--only Key1,Key2] [--seed 1864]"""
import argparse, os, subprocess, sys
import numpy as np
from PIL import Image, ImageFilter

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..')
OUT = os.path.join(ROOT, 'Reference', 'Campaign1851', 'Buildings')
CLIENT = r"R:\Onedrive\Dokumenter\Unreal Projects\Game1864\pinokio_agent\skills\api\comfy.git\clients\txt2img.py"
STYLE = ("small isolated object with lots of empty white space around it, isometric 3/4 view game asset illustration, 1850s Denmark, highly detailed painterly, soft daylight, "
         "small cobblestone and grass base plate under the building, isolated on plain pure white background, centered, full building visible, no people")
BUILDINGS = {
    'Rifle_Workshop': 'a state rifle workshop, two storey red brick workshop with large windows, racks of muskets, crates, a small chimney',
    'Cannon_Foundry': 'a cannon foundry, red brick industrial hall with tall chimneys and smoke, bronze cannon barrels and wooden gun carriages in the yard',
    'Ammunition_Works': 'an ammunition works, long low red brick factory, powder barrels, crates of cartridges, earth bank around it',
    'Stud_Farm': 'a royal stud farm, long half-timbered thatched stables around a yard, paddock fence, horses grazing',
    'Remount_Depot': 'a cavalry remount depot, long half-timbered stables with a fenced paddock, hay, cavalry horses',
    'Schoolhouse': 'a village schoolhouse, small whitewashed brick building with red tile roof, school bell, picket fence',
    'Town_Hall': 'a town hall, neoclassical red brick building with a clock tower and Danish flag, stone steps',
    'Post_Office': 'a royal post office, yellow plastered two storey building with a red post coach in front, crown sign',
    'Hospital': 'a town hospital, large three storey red brick building with many windows, garden and fence',
    'Harbor_Building': 'a customs house by a harbour quay, red brick with tall roof, barrels and crates on the quay, small sailing boat',
    'Lighthouse': 'a white stone lighthouse on a rocky shore with a small keeper house',
    'Merchant_House': 'a merchant yard, half-timbered yellow buildings around a courtyard with a warehouse, carts and sacks',
    'Brewery': 'a brewery and distillery, red brick buildings with a chimney, copper kettles, stacked beer barrels',
    'Brickworks': 'a brickworks, a round kiln with tall chimney, drying sheds and stacks of red bricks, clay pit',
    'Sawmill': 'a water-driven sawmill, timber building with a water wheel, stacks of logs and planks',
    'Machine_Workshop': 'a machine workshop, red brick hall with iron framed windows, steam engine, chimney, iron parts',
    'Textile_Mill': 'a textile mill, large four storey red brick mill with many windows and a tall chimney',
    'Inn': 'a Danish country inn (kro), long white half-timbered thatched building with a coach and horses in the yard',
}


def key_out(path_in, path_out):
    """Near-white connected to the border -> transparent; a soft edge; 512 px."""
    im = Image.open(path_in).convert('RGB')
    a = np.asarray(im).astype(np.int16)
    white = (a.min(axis=2) > 232) & ((a.max(axis=2) - a.min(axis=2)) < 18)
    h, w = white.shape
    seen = np.zeros_like(white)
    stack = [(0, x) for x in range(w)] + [(h - 1, x) for x in range(w)] + [(y, 0) for y in range(h)] + [(y, w - 1) for y in range(h)]
    while stack:
        y, x = stack.pop()
        if y < 0 or x < 0 or y >= h or x >= w or seen[y, x] or not white[y, x]:
            continue
        seen[y, x] = True
        stack.extend(((y + 1, x), (y - 1, x), (y, x + 1), (y, x - 1)))
    alpha = Image.fromarray(np.where(seen, 0, 255).astype(np.uint8)).filter(ImageFilter.GaussianBlur(1.2))
    rgba = im.copy()
    rgba.putalpha(alpha)
    rgba.resize((512, 512), Image.LANCZOS).save(path_out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--base', required=True)
    ap.add_argument('--only', default='')
    ap.add_argument('--seed', type=int, default=1864)
    ap.add_argument('--ckpt', default='juggernautXL_ragnarokBy.safetensors')
    a = ap.parse_args()
    only = set(k for k in a.only.split(',') if k)
    os.makedirs(OUT, exist_ok=True)
    for i, (key, what) in enumerate(BUILDINGS.items()):
        if only and key not in only:
            continue
        raw = os.path.join(OUT, '_raw_' + key + '.png')
        subprocess.check_call([sys.executable, CLIENT, '--base', a.base, '--ckpt', a.ckpt, '--out', raw, '--seed', str(a.seed + i),
                               '--prompt', 'isometric illustration of ' + what + ', ' + STYLE])
        key_out(raw, os.path.join(OUT, 'T_Bld_' + key + '.png'))
        os.remove(raw)
        print('card', key)


if __name__ == '__main__':
    main()
