"""Portraits for the officers and ministers (PROJECT 1864): a pool of painted head-and-shoulders portraits in the
manner of the 1850s, generated by ComfyUI (SDXL) through pinokio_agent/skills/api/comfy.git/clients/txt2img.py,
256 x 320, written to Reference/Campaign1851/Portraits/T_Portrait_<Kind>_<NN>.png. The game gives each person one
from his pool by his name (they are types of the time, not likenesses).
Usage: python Tools/Campaign/make_portraits.py --base <comfy url> [--count 12]"""
import argparse, os, random, subprocess, sys
from PIL import Image

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..')
OUT = os.path.join(ROOT, 'Reference', 'Campaign1851', 'Portraits')
CLIENT = r"R:\Onedrive\Dokumenter\Unreal Projects\Game1864\pinokio_agent\skills\api\comfy.git\clients\txt2img.py"
STYLE = "oil painting portrait, 1850s Danish Golden Age portrait painting, head and shoulders, three-quarter view, soft studio light, dark plain background, fine brushwork, museum quality"
NEG = "photo, modern, text, watermark, signature, frame, cartoon, anime, deformed, extra limbs, sunglasses, woman"
KINDS = {
    'Officer': "a Danish army captain or major of 1850, dark blue uniform tunic with red collar and silver buttons, {age} man, {hair}",
    'General': "a Danish army general of 1850, dark blue uniform with red collar, heavy gold epaulettes, orders and medals on the chest, {age} man, {hair}",
    'Minister': "a Danish government minister of 1850, black frock coat, white high collar and black cravat, {age} gentleman, {hair}",
}
AGES = ['young', 'middle-aged', 'grey-haired older', 'weathered middle-aged', 'stern older']
HAIRS = ['clean shaven, side parting', 'mutton chop sideburns', 'full beard', 'moustache and side whiskers', 'receding hairline, sideburns',
         'curly dark hair, moustache', 'short grey hair, chin beard', 'balding with long sideburns']


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--base', required=True)
    ap.add_argument('--count', type=int, default=12)
    ap.add_argument('--ckpt', default='juggernautXL_ragnarokBy.safetensors')
    a = ap.parse_args()
    os.makedirs(OUT, exist_ok=True)
    rng = random.Random(1864)
    for kind, text in KINDS.items():
        for n in range(a.count):
            out = os.path.join(OUT, 'T_Portrait_%s_%02d.png' % (kind, n))
            if os.path.exists(out):
                continue
            raw = out + '.raw.png'
            prompt = text.format(age=rng.choice(AGES), hair=rng.choice(HAIRS)) + ', ' + STYLE
            subprocess.check_call([sys.executable, CLIENT, '--base', a.base, '--ckpt', a.ckpt, '--out', raw, '--seed', str(5000 + n * 31 + len(kind)),
                                   '--width', '832', '--height', '1024', '--prompt', prompt, '--negative', NEG])
            Image.open(raw).convert('RGB').resize((256, 320), Image.LANCZOS).save(out)
            os.remove(raw)
            print('portrait', kind, n)


if __name__ == '__main__':
    main()
